"""Catalogos cerrados definidos por el cliente (requerimientos funcionales).

Estos valores NO se alteran: son los establecidos por la empresa.
"""

TIPO_TRAMITE_SEGURO = "SEGURO"
TIPO_TRAMITE_SUBSIDIO = "SUBSIDIO"
TIPO_TRAMITE_VALORES = (TIPO_TRAMITE_SEGURO, TIPO_TRAMITE_SUBSIDIO)

RIESGO_SEGURO_VALORES = (
    "ALTA TITULAR",
    "ALTA DERECHOHABIENTE",
    "CONDICION DEL ASEGURADO",
    "AUDITORIA",
    "FISCALIZACION POSTERIOR",
    "BAJA TITULAR",
    "BAJA DERECHOHABIENTE",
    "LACTANCIA",
    "ENFERMEDAD",
)

DECISION_SEGURO_VALORES = (
    "BAJA DE OFICIO",
    "RESOLUCION DE MULTA",
)

RIESGO_SUBSIDIO_VALORES = (
    "LACTANCIA",
    "ENFERMEDAD",
    "MATERNIDAD",
    "SEPELIO",
    "REINTEGRO",
    "FISCALIZACION POSTERIOR",
)

DECISION_SUBSIDIO_VALORES = (
    "BAJA DE OFICIO",
    "DENEGATORIA",
    "IMPROCEDENTE",
    "EN PARTE",
)

DECISION_RECONSIDERACION_VALORES = (
    "FUNDADO",
    "INFUNDADO",
    "EN PARTE",
)

MEDIO_COMUNICACION_VALORES = (
    "CORREO",
    "PRESENCIAL",
    "VIRTUAL",
)

# Formatos
EXP_SGD_LONGITUD = 16
RUC_LONGITUD = 11
DNI_CE_MIN = 5
DNI_CE_MAX = 10
NUMERO_RESOLUCION_LONGITUD = 4
NUMERO_NOTA_DERIVACION_LONGITUD = 6
MAX_ENTIDAD_EMPLEADORA = 50
MAX_ASEGURADO_TITULAR = 50
MAX_MOTIVO = 100
MAX_APELLIDOS_NOMBRES = 50

# Auditoria
ACCIONES_AUDITORIA = (
    "LOGIN",
    "CREAR_SOLICITUD",
    "EDITAR_SOLICITUD",
    "CREAR_RESOLUCION",
    "EDITAR_RESOLUCION",
    "CREAR_RECONSIDERACION",
    "CREAR_APELACION",
    "CREAR_USUARIO",
    "EDITAR_USUARIO",
    "BLOQUEAR_USUARIO",
    "DESBLOQUEAR_USUARIO",
    "ELIMINAR_USUARIO",
    "CAMBIAR_ROL",
    "BACKUP",
    "ELIMINAR_BACKUP",
    "RESTAURAR_BACKUP",
    "IMPORTACION",
    "EXPORTAR_REPORTE",
)

ORIGEN_REGISTRO = "REGISTRO"
ORIGEN_MIGRACION = "MIGRACION"